name: plural_noun
description: Converts a English singular noun to a plural noun using a set of rules.
version: 0.0.2
homepage: https://github.com/efficientyboosters/plural_noun
repository: https://github.com/efficientyboosters/plural_noun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
