name: plural_noun
description: Converts a English singular noun to a plural noun using a set of rules.
version: 0.2.0
repository: https://github.com/domain-centric/plural_noun

environment:
  sdk: ^3.8.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  shouldly: ^0.5.0+1
  test: ^1.24.0

flutter:
